[package]
name = "test-sol-log-data"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_sdk = "0.6.1"
arch_program = "0.6.1"
borsh = { version = "1.4.0", features = ["derive"] }
log = "0.4"

[dev-dependencies]

[lib]
path = "src/lib.rs"
