[package]
name = "create-new-account"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_program = "0.6.1"
borsh = "1.5.3"
hex = "0.4.3"
arch_sdk = "0.6.1"
bitcoin = { version = "0.32.3", features = ["serde"] }
rand = "0.8.5"
